/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JPLearnerClassContent {
  schemaVersion: 1;
  classId: string;
  date: string;
  label: string;
  vocab?: Vocab[];
  grammar?: Grammar[];
  kanji?: Kanji[];
  notes?: Note[];
}
export interface Vocab {
  id: string;
  type: "vocab";
  kanji: string;
  kana: string;
  romaji: string;
  es: string;
  pos?: string;
  /**
   * @minItems 1
   */
  tokens: [Token, ...Token[]];
  example?: Sentence;
  /**
   * @minItems 1
   */
  tags: [string, ...string[]];
}
export interface Token {
  surface: string;
  reading: string;
  isKanji: boolean;
  kanji?: string[];
}
export interface Sentence {
  kanji: string;
  kana: string;
  romaji: string;
  es: string;
  tokens?: Token[];
}
export interface Grammar {
  id: string;
  type: "grammar";
  pattern: string;
  es: string;
  /**
   * @minItems 1
   */
  examples: [Sentence, ...Sentence[]];
  /**
   * @minItems 1
   */
  tags: [string, ...string[]];
}
export interface Kanji {
  id: string;
  type: "kanji";
  char: string;
  readings: {
    on?: string[];
    kun?: string[];
  };
  es: string;
  seenIn: string[];
}
export interface Note {
  id: string;
  type: "note";
  es: string;
  /**
   * @minItems 1
   */
  tags: [string, ...string[]];
}
